import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the project root of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const outdir = ".obsidian/plugins/obsidian-todotxt";

// Create output directory if it doesn't exist
if (!fs.existsSync(outdir)){
    fs.mkdirSync(outdir, { recursive: true });
}

// Copy manifest and styles
const copyFiles = () => {
  if (fs.existsSync("manifest.json")) {
    fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
  }
  if (fs.existsSync("styles.css")) {
    fs.copyFileSync("styles.css", path.join(outdir, "styles.css"));
  }
  if (fs.existsSync(path.join(outdir, "main.js"))) {
    fs.copyFileSync(path.join(outdir, "main.js"), "main.js");
  }
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
	],
	format: 'cjs',
	target: 'es2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: path.join(outdir, 'main.js'),
});

if (prod) {
	await context.rebuild();
	copyFiles();
	process.exit(0);
} else {
	copyFiles();
	await context.watch();
	// Watch manifest and styles
	fs.watch("manifest.json", () => copyFiles());
	fs.watch("styles.css", () => copyFiles());
}
