/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the project root of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TodoTxtPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// parser.ts
function parseTodoLine(line) {
  const trimmed = line.trim();
  let remaining = trimmed;
  let completed = false;
  let priority = null;
  if (remaining.startsWith("x ")) {
    completed = true;
    remaining = remaining.substring(2).trim();
  }
  const priorityMatch = remaining.match(/^\(([A-Z])\)\b/);
  if (priorityMatch) {
    priority = priorityMatch[1];
    remaining = remaining.substring(priorityMatch[0].length).trim();
  }
  const description = remaining;
  const tokens = description.split(/\s+/).filter((t) => t.length > 0);
  const projects = [];
  const contexts = [];
  const metadata = {};
  for (const token of tokens) {
    if (token.startsWith("+") && token.length > 1) {
      projects.push(token.substring(1));
    } else if (token.startsWith("@") && token.length > 1) {
      contexts.push(token.substring(1));
    } else {
      const colonIdx = token.indexOf(":");
      if (colonIdx > 0 && colonIdx < token.length - 1 && !token.startsWith("+") && !token.startsWith("@")) {
        const key = token.substring(0, colonIdx);
        const val = token.substring(colonIdx + 1);
        if (/^[a-zA-Z0-9_-]+$/.test(key) && !val.startsWith("//")) {
          metadata[key] = val;
        }
      }
    }
  }
  const completionDate = metadata.complete || null;
  const creationDate = metadata.creation || null;
  return {
    originalLine: trimmed,
    completed,
    priority,
    completionDate,
    creationDate,
    description,
    projects,
    contexts,
    metadata
  };
}
function updateMetadataInDescription(description, key, newValue) {
  const regex = new RegExp(`(?:^|\\s)${key}:[^\\s]+`, "g");
  if (newValue === null) {
    return description.replace(regex, "").replace(/\s+/g, " ").trim();
  } else {
    const updatedToken = `${key}:${newValue}`;
    let replaced = false;
    const result = description.replace(regex, (match) => {
      replaced = true;
      const leadingSpace = match.startsWith(" ") || match.startsWith("	") ? match[0] : " ";
      return `${leadingSpace}${updatedToken}`;
    });
    if (replaced) {
      return result.replace(/\s+/g, " ").trim();
    } else {
      return `${description.trim()} ${updatedToken}`.trim();
    }
  }
}
function stringifyTodo(task) {
  const parts = [];
  if (task.completed) {
    parts.push("x");
  }
  if (task.priority) {
    parts.push(`(${task.priority})`);
  }
  if (task.description) {
    parts.push(task.description);
  }
  return parts.join(" ");
}
function formatDate(date) {
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}
function calculateNextDueDate(dueDateStr, completionDateStr, recStr) {
  const isStrict = recStr.startsWith("+");
  const cleanedRec = isStrict ? recStr.substring(1) : recStr;
  const match = cleanedRec.match(/^(\d*)([dwmy])$/);
  if (!match) {
    return formatDate(new Date(Date.now() + 864e5));
  }
  const amount = match[1] ? parseInt(match[1], 10) : 1;
  const period = match[2];
  let baseDate = /* @__PURE__ */ new Date();
  if (dueDateStr) {
    const parsed = new Date(dueDateStr);
    if (!isNaN(parsed.getTime())) {
      baseDate = parsed;
    }
  } else if (completionDateStr) {
    const parsed = new Date(completionDateStr);
    if (!isNaN(parsed.getTime())) {
      baseDate = parsed;
    }
  }
  const nextDate = new Date(baseDate.getTime());
  if (period === "d") {
    nextDate.setDate(nextDate.getDate() + amount);
  } else if (period === "w") {
    nextDate.setDate(nextDate.getDate() + amount * 7);
  } else if (period === "m") {
    nextDate.setMonth(nextDate.getMonth() + amount);
  } else if (period === "y") {
    nextDate.setFullYear(nextDate.getFullYear() + amount);
  }
  return formatDate(nextDate);
}
function sortTasksByDueDate(tasks) {
  return [...tasks].sort((a, b) => {
    if (a.completed !== b.completed) {
      return a.completed ? 1 : -1;
    }
    const aDue = a.metadata.due || null;
    const bDue = b.metadata.due || null;
    if (aDue && bDue) {
      if (aDue !== bDue)
        return aDue.localeCompare(bDue);
    } else if (aDue) {
      return -1;
    } else if (bDue) {
      return 1;
    }
    const aPrio = a.priority || "Z";
    const bPrio = b.priority || "Z";
    if (aPrio !== bPrio)
      return aPrio.localeCompare(bPrio);
    return a.description.localeCompare(b.description);
  });
}
function sortTasksByPriority(tasks) {
  return [...tasks].sort((a, b) => {
    if (a.completed !== b.completed) {
      return a.completed ? 1 : -1;
    }
    const aPrio = a.priority || "Z";
    const bPrio = b.priority || "Z";
    if (aPrio !== bPrio) {
      return aPrio.localeCompare(bPrio);
    }
    const aDue = a.metadata.due || "9999-12-31";
    const bDue = b.metadata.due || "9999-12-31";
    if (aDue !== bDue)
      return aDue.localeCompare(bDue);
    return a.description.localeCompare(b.description);
  });
}
function extractContexts(content) {
  const contextSet = /* @__PURE__ */ new Set();
  const lines = content.split(/\r?\n/);
  for (const line of lines) {
    const task = parseTodoLine(line);
    for (const ctx of task.contexts) {
      contextSet.add(ctx);
    }
  }
  return Array.from(contextSet).sort();
}
function extractProjects(content) {
  const projectSet = /* @__PURE__ */ new Set();
  const lines = content.split(/\r?\n/);
  for (const line of lines) {
    const task = parseTodoLine(line);
    for (const proj of task.projects) {
      projectSet.add(proj);
    }
  }
  return Array.from(projectSet).sort();
}
function groupAndSortTasks(tasks, sortBy) {
  const groups = {};
  for (const task of tasks) {
    const context = task.contexts.length > 0 ? `@${task.contexts[0]}` : "No Context";
    const project = task.projects.length > 0 ? `+${task.projects[0]}` : "No Project";
    if (!groups[context]) {
      groups[context] = {};
    }
    if (!groups[context][project]) {
      groups[context][project] = [];
    }
    groups[context][project].push(task);
  }
  const sortedContexts = Object.keys(groups).sort((a, b) => {
    if (a === "No Context")
      return 1;
    if (b === "No Context")
      return -1;
    return a.localeCompare(b);
  });
  const outputLines = ["", "", ""];
  for (const ctx of sortedContexts) {
    outputLines.push("---");
    outputLines.push(`## ${ctx}`);
    const sortedProjects = Object.keys(groups[ctx]).sort((a, b) => {
      if (a === "No Project")
        return 1;
      if (b === "No Project")
        return -1;
      return a.localeCompare(b);
    });
    for (const proj of sortedProjects) {
      outputLines.push(`### ${proj}`);
      const sortedTasks = sortBy === "due" ? sortTasksByDueDate(groups[ctx][proj]) : sortTasksByPriority(groups[ctx][proj]);
      for (const t of sortedTasks) {
        outputLines.push(stringifyTodo(t));
      }
      outputLines.push("");
    }
  }
  return outputLines.join("\n").replace(/\s+$/, "") + "\n";
}

// highlighter.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var import_autocomplete = require("@codemirror/autocomplete");

// autocomplete.ts
function createTodoCompletionSource(getFileContent) {
  return (context) => {
    const word = context.matchBefore(/[@+]\w*/);
    if (!word)
      return null;
    const text = word.text;
    const isContext = text.startsWith("@");
    const isProject = text.startsWith("+");
    if (!isContext && !isProject)
      return null;
    const filterPrefix = text.slice(1).toLowerCase();
    const fileContent = getFileContent();
    const items = isContext ? extractContexts(fileContent) : extractProjects(fileContent);
    const completions = items.filter((item) => item.toLowerCase().startsWith(filterPrefix)).map((item) => ({
      label: item,
      detail: isContext ? "context" : "project",
      // Complete to the full tag (e.g., "@context")
      apply: isContext ? `@${item}` : `+${item}`,
      type: "variable"
    }));
    if (completions.length === 0)
      return null;
    return {
      from: word.from,
      options: completions
    };
  };
}

// highlighter.ts
function createTodoHighlighterPlugin(plugin) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.decorations = this.buildDecorations(view);
      }
      update(update) {
        if (update.docChanged || update.viewportChanged) {
          this.decorations = this.buildDecorations(update.view);
        }
      }
      buildDecorations(view) {
        const builder = new import_state.RangeSetBuilder();
        const activeFile = plugin.app.workspace.getActiveFile();
        if (!activeFile)
          return builder.finish();
        if (!plugin.isTargetFile(activeFile.path))
          return builder.finish();
        const settings = plugin.settings;
        const priorityColor = settings.priorityColor || "#c17171";
        const dueDateColor = settings.dueDateColor || "#e28743";
        const overdueDateColor = settings.overdueDateColor || "#ff3b30";
        const projectColor = settings.projectColor || "#5c91e6";
        const contextColor = settings.contextColor || "#6a8390";
        const recColor = settings.recColor || "#8a3ab9";
        const priorityDeco = import_view.Decoration.mark({ attributes: { style: `color: ${priorityColor}; font-weight: bold;` } });
        const dueDeco = import_view.Decoration.mark({ attributes: { style: `color: ${dueDateColor}; font-weight: bold;` } });
        const overdueDeco = import_view.Decoration.mark({ attributes: { style: `color: ${overdueDateColor}; font-weight: bold;` } });
        const projectDeco = import_view.Decoration.mark({ attributes: { style: `color: ${projectColor}; font-weight: 500;` } });
        const contextDeco = import_view.Decoration.mark({ attributes: { style: `color: ${contextColor}; font-weight: 500;` } });
        const recDeco = import_view.Decoration.mark({ attributes: { style: `color: ${recColor}; font-style: italic;` } });
        const completedDeco = import_view.Decoration.mark({
          attributes: {
            style: "color: var(--text-muted) !important; text-decoration: line-through !important; opacity: 0.6;"
          }
        });
        for (const { from, to } of view.visibleRanges) {
          let pos = from;
          while (pos <= to) {
            const line = view.state.doc.lineAt(pos);
            const lineText = line.text;
            if (lineText.trim().startsWith("x ")) {
              const lineStart = line.from;
              const lineEnd = line.to;
              if (lineStart < lineEnd) {
                builder.add(lineStart, lineEnd, completedDeco);
              }
            } else {
              const matches = [];
              const priorityRegex = /\([A-Z]\)/g;
              let match;
              while ((match = priorityRegex.exec(lineText)) !== null) {
                matches.push({
                  start: line.from + match.index,
                  end: line.from + match.index + match[0].length,
                  deco: priorityDeco
                });
              }
              const dueRegex = /\bdue:\d{4}-\d{2}-\d{2}\b/g;
              while ((match = dueRegex.exec(lineText)) !== null) {
                const dueText = match[0];
                const dateVal = dueText.substring(4);
                const today = /* @__PURE__ */ new Date();
                const yyyy = today.getFullYear();
                const mm = String(today.getMonth() + 1).padStart(2, "0");
                const dd = String(today.getDate()).padStart(2, "0");
                const todayStr = `${yyyy}-${mm}-${dd}`;
                const isOverdue = dateVal <= todayStr;
                matches.push({
                  start: line.from + match.index,
                  end: line.from + match.index + match[0].length,
                  deco: isOverdue ? overdueDeco : dueDeco
                });
              }
              const projectRegex = /(\s|^)(\+[a-zA-Z0-9_-]+)/g;
              while ((match = projectRegex.exec(lineText)) !== null) {
                const leadingSpaceLen = match[1].length;
                const tokenStart = line.from + match.index + leadingSpaceLen;
                const tokenEnd = tokenStart + match[2].length;
                matches.push({ start: tokenStart, end: tokenEnd, deco: projectDeco });
              }
              const contextRegex = /(\s|^)(@[a-zA-Z0-9_-]+)/g;
              while ((match = contextRegex.exec(lineText)) !== null) {
                const leadingSpaceLen = match[1].length;
                const tokenStart = line.from + match.index + leadingSpaceLen;
                const tokenEnd = tokenStart + match[2].length;
                matches.push({ start: tokenStart, end: tokenEnd, deco: contextDeco });
              }
              const recRegex = /\brec:\+?\d*[dwmy]\b/g;
              while ((match = recRegex.exec(lineText)) !== null) {
                matches.push({
                  start: line.from + match.index,
                  end: line.from + match.index + match[0].length,
                  deco: recDeco
                });
              }
              matches.sort((a, b) => a.start - b.start);
              let lastAddedEnd = -1;
              for (const m of matches) {
                if (m.start >= lastAddedEnd && m.start < m.end && m.end <= view.state.doc.length) {
                  builder.add(m.start, m.end, m.deco);
                  lastAddedEnd = m.end;
                }
              }
            }
            pos = line.to + 1;
          }
        }
        return builder.finish();
      }
    },
    {
      decorations: (v) => v.decorations
    }
  );
}
function createTodoAutocompleteExtension(plugin) {
  const completionSource = (context) => {
    const activeFile = plugin.app.workspace.getActiveFile();
    if (!activeFile || !plugin.isTargetFile(activeFile.path)) {
      return null;
    }
    const content = context.state.doc.toString();
    const source = createTodoCompletionSource(() => content);
    return source(context);
  };
  return (0, import_autocomplete.autocompletion)({
    override: [completionSource]
  });
}
function createTodoPostProcessor(plugin) {
  return (el, ctx) => {
    if (!plugin.isTargetFile(ctx.sourcePath))
      return;
    const settings = plugin.settings;
    const textContent = el.textContent || "";
    if (textContent.trim().startsWith("x ")) {
      el.style.color = "var(--text-muted)";
      el.style.textDecoration = "line-through";
      el.style.opacity = "0.6";
      return;
    }
    const priorityColor = settings.priorityColor || "#c17171";
    const dueDateColor = settings.dueDateColor || "#e28743";
    const overdueDateColor = settings.overdueDateColor || "#ff3b30";
    const projectColor = settings.projectColor || "#5c91e6";
    const contextColor = settings.contextColor || "#6a8390";
    const recColor = settings.recColor || "#8a3ab9";
    const highlightElementText = (node) => {
      if (node.nodeType === Node.TEXT_NODE) {
        const text = node.textContent || "";
        const tokens = text.split(/(\s+)/);
        const fragment = document.createDocumentFragment();
        let hasMatches = false;
        for (const token of tokens) {
          if (token.trim().length === 0) {
            fragment.appendChild(document.createTextNode(token));
            continue;
          }
          if (/^\([A-Z]\)$/.test(token)) {
            const span = document.createElement("span");
            span.style.color = priorityColor;
            span.style.fontWeight = "bold";
            span.textContent = token;
            fragment.appendChild(span);
            hasMatches = true;
          } else if (/^due:\d{4}-\d{2}-\d{2}$/.test(token)) {
            const dateVal = token.substring(4);
            const today = /* @__PURE__ */ new Date();
            const yyyy = today.getFullYear();
            const mm = String(today.getMonth() + 1).padStart(2, "0");
            const dd = String(today.getDate()).padStart(2, "0");
            const todayStr = `${yyyy}-${mm}-${dd}`;
            const isOverdue = dateVal <= todayStr;
            const span = document.createElement("span");
            span.style.color = isOverdue ? overdueDateColor : dueDateColor;
            span.style.fontWeight = "bold";
            span.textContent = token;
            fragment.appendChild(span);
            hasMatches = true;
          } else if (/^\+[a-zA-Z0-9_-]+$/.test(token)) {
            const span = document.createElement("span");
            span.style.color = projectColor;
            span.style.fontWeight = "500";
            span.textContent = token;
            fragment.appendChild(span);
            hasMatches = true;
          } else if (/^@[a-zA-Z0-9_-]+$/.test(token)) {
            const span = document.createElement("span");
            span.style.color = contextColor;
            span.style.fontWeight = "500";
            span.textContent = token;
            fragment.appendChild(span);
            hasMatches = true;
          } else if (/^rec:\+?\d*[dwmy]$/.test(token)) {
            const span = document.createElement("span");
            span.style.color = recColor;
            span.style.fontStyle = "italic";
            span.textContent = token;
            fragment.appendChild(span);
            hasMatches = true;
          } else {
            fragment.appendChild(document.createTextNode(token));
          }
        }
        if (hasMatches && node.parentNode) {
          node.parentNode.replaceChild(fragment, node);
        }
      } else {
        const children = Array.from(node.childNodes);
        for (const child of children) {
          highlightElementText(child);
        }
      }
    };
    highlightElementText(el);
  };
}

// main.ts
var DEFAULT_SETTINGS = {
  todoPath: "todo.md",
  additionalPaths: "",
  archivePath: "completed_todo.md",
  priorityColor: "#c17171",
  // Soft rose/red
  dueDateColor: "#e28743",
  // Sleek vibrant orange
  overdueDateColor: "#ff3b30",
  // Vibrant warning red
  projectColor: "#5c91e6",
  // Modern premium blue
  contextColor: "#6a8390",
  // Professional blue-gray
  recColor: "#8a3ab9"
  // Vibrant recurrence purple
};
var TodoTxtPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.fileCache = {};
    this.isWritingFile = false;
  }
  async onload() {
    await this.loadSettings();
    this.registerEditorExtension(createTodoHighlighterPlugin(this));
    this.registerEditorExtension(createTodoAutocompleteExtension(this));
    this.registerMarkdownPostProcessor(createTodoPostProcessor(this));
    this.addRibbonIcon("list-checks", "Todo.txt Control Panel", () => {
      new TodoControlPanelModal(this.app, this).open();
    });
    this.addCommand({
      id: "todotxt-toggle-completion",
      name: "Toggle Completion on Current Line",
      editorCallback: (editor, view) => {
        this.toggleCompletion(editor, view);
      }
    });
    this.addCommand({
      id: "todotxt-sort-due",
      name: "Sort by Due Date",
      callback: () => this.processActiveFile("due")
    });
    this.addCommand({
      id: "todotxt-sort-priority",
      name: "Sort by Priority",
      callback: () => this.processActiveFile("priority")
    });
    this.addCommand({
      id: "todotxt-archive-completed",
      name: "Archive Completed Tasks",
      callback: () => this.archiveCompletedTasks()
    });
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (!(file instanceof import_obsidian.TFile) || this.isWritingFile)
          return;
        if (!this.isTargetFile(file.path))
          return;
        await this.handleFileModification(file);
      })
    );
    this.app.workspace.onLayoutReady(() => {
      this.initializeFileCache();
    });
    this.addSettingTab(new TodoSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf.view instanceof import_obsidian.MarkdownView) {
        leaf.view.previewMode?.rerender(true);
        const editor = leaf.view.editor;
        if (editor?.cm) {
          editor.cm.dispatch({});
        }
      }
    });
  }
  /**
   * Helper to check if a file path is a designated todo target file
   */
  isTargetFile(filePath) {
    const normalize = (p) => p.replace(/^\.\//, "").trim().toLowerCase();
    const normalizedPath = normalize(filePath);
    if (normalizedPath === normalize(this.settings.todoPath))
      return true;
    const additional = this.settings.additionalPaths.split(",").map((p) => normalize(p)).filter((p) => p.length > 0);
    return additional.includes(normalizedPath);
  }
  /**
   * Reads all target files and initializes the in-memory line cache.
   */
  async initializeFileCache() {
    const files = this.app.vault.getFiles();
    for (const file of files) {
      if (this.isTargetFile(file.path)) {
        const content = await this.app.vault.read(file);
        this.fileCache[file.path] = content.split(/\r?\n/);
      }
    }
  }
  /**
   * Detects newly completed tasks upon manual file edits and handles recurrence.
   */
  async handleFileModification(file) {
    const content = await this.app.vault.read(file);
    const newLines = content.split(/\r?\n/);
    const cachedLines = this.fileCache[file.path] || [];
    const newTasks = newLines.map((line) => parseTodoLine(line));
    const cachedTasks = cachedLines.map((line) => parseTodoLine(line));
    const updatedLines = [...newLines];
    let insertedCount = 0;
    let fileModified = false;
    for (let i = 0; i < newTasks.length; i++) {
      const newTask = newTasks[i];
      if (newTask.completed) {
        const wasUncompleted = cachedTasks.some(
          (oldTask) => !oldTask.completed && oldTask.description === newTask.description && oldTask.priority === newTask.priority
        );
        if (wasUncompleted) {
          const todayStr = formatDate(/* @__PURE__ */ new Date());
          if (!newTask.metadata.complete) {
            newTask.completionDate = todayStr;
            newTask.metadata.complete = todayStr;
            newTask.description = updateMetadataInDescription(newTask.description, "complete", todayStr);
            updatedLines[i + insertedCount] = stringifyTodo(newTask);
            fileModified = true;
          }
          if (newTask.metadata.rec) {
            const nextDueExpected = calculateNextDueDate(
              newTask.metadata.due || null,
              newTask.completionDate || todayStr,
              newTask.metadata.rec
            );
            const alreadyHasNext = newTasks.some(
              (t) => !t.completed && t.description === newTask.description && t.metadata.due === nextDueExpected
            );
            if (!alreadyHasNext) {
              const nextDue = calculateNextDueDate(
                newTask.metadata.due || null,
                newTask.completionDate || todayStr,
                newTask.metadata.rec
              );
              let nextDescription = updateMetadataInDescription(newTask.description, "due", nextDue);
              nextDescription = updateMetadataInDescription(nextDescription, "complete", null);
              const nextMetadata = Object.assign({}, newTask.metadata, { due: nextDue });
              delete nextMetadata.complete;
              const nextTask = {
                originalLine: "",
                completed: false,
                priority: newTask.priority,
                completionDate: null,
                creationDate: null,
                description: nextDescription,
                projects: newTask.projects,
                contexts: newTask.contexts,
                metadata: nextMetadata
              };
              const stringifiedNext = stringifyTodo(nextTask);
              const insertIndex = i + 1 + insertedCount;
              updatedLines.splice(insertIndex, 0, stringifiedNext);
              insertedCount++;
              fileModified = true;
            }
          }
        }
      }
    }
    this.fileCache[file.path] = newLines;
    if (fileModified) {
      this.isWritingFile = true;
      try {
        const updatedContent = updatedLines.join("\n");
        await this.app.vault.modify(file, updatedContent);
        this.fileCache[file.path] = updatedContent.split(/\r?\n/);
        if (insertedCount > 0) {
          new import_obsidian.Notice(`Completed tasks saved & generated ${insertedCount} recurring task(s) below!`);
        } else {
          new import_obsidian.Notice("Completed task saved!");
        }
      } catch (err) {
        console.error("Failed to write completed task:", err);
      } finally {
        this.isWritingFile = false;
      }
    }
  }
  /**
   * Toggles task completion on the current line of the active editor.
   * Handles recurrence instantly in-place!
   */
  async toggleCompletion(editor, view) {
    const activeFile = view.file;
    if (!activeFile)
      return;
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    if (lineText.trim().length === 0)
      return;
    const task = parseTodoLine(lineText);
    const newTasksToInsert = [];
    if (task.completed) {
      task.completed = false;
      task.completionDate = null;
      task.description = updateMetadataInDescription(task.description, "complete", null);
      if (task.metadata.complete) {
        delete task.metadata.complete;
      }
      editor.setLine(cursor.line, stringifyTodo(task));
      new import_obsidian.Notice("Task marked incomplete");
    } else {
      task.completed = true;
      const todayStr = formatDate(/* @__PURE__ */ new Date());
      task.completionDate = todayStr;
      task.description = updateMetadataInDescription(task.description, "complete", todayStr);
      task.metadata.complete = todayStr;
      if (task.metadata.rec) {
        const nextDue = calculateNextDueDate(
          task.metadata.due || null,
          task.completionDate,
          task.metadata.rec
        );
        let nextDescription = updateMetadataInDescription(task.description, "due", nextDue);
        nextDescription = updateMetadataInDescription(nextDescription, "complete", null);
        const nextMetadata = Object.assign({}, task.metadata, { due: nextDue });
        delete nextMetadata.complete;
        const nextTask = {
          originalLine: "",
          completed: false,
          priority: task.priority,
          completionDate: null,
          creationDate: null,
          description: nextDescription,
          projects: task.projects,
          contexts: task.contexts,
          metadata: nextMetadata
        };
        newTasksToInsert.push(stringifyTodo(nextTask));
      }
      editor.setLine(cursor.line, stringifyTodo(task));
      if (newTasksToInsert.length > 0) {
        const nextLinePos = { line: cursor.line + 1, ch: 0 };
        editor.replaceRange(newTasksToInsert.join("\n") + "\n", nextLinePos);
        new import_obsidian.Notice("Task completed! Created recurring instance below.");
      } else {
        new import_obsidian.Notice("Task completed!");
      }
    }
    if (this.isTargetFile(activeFile.path)) {
      const updatedContent = editor.getValue();
      this.fileCache[activeFile.path] = updatedContent.split(/\r?\n/);
    }
  }
  /**
   * Restructures, groups (Context -> Project), and sorts the tasks in the active file.
   * Preserves the top 3 blank lines for quick entry!
   */
  async processActiveFile(sortBy) {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView || !activeView.file) {
      new import_obsidian.Notice("No active file open!");
      return;
    }
    const file = activeView.file;
    if (!this.isTargetFile(file.path)) {
      new import_obsidian.Notice("Active file is not a designated Todo.txt file!");
      return;
    }
    const content = await this.app.vault.read(file);
    const tasks = content.split(/\r?\n/).map((line) => line.trim()).filter((line) => line.length > 0 && !line.startsWith("#") && line !== "---").map((line) => parseTodoLine(line));
    if (tasks.length === 0) {
      new import_obsidian.Notice("No tasks found in the file!");
      return;
    }
    const newContent = groupAndSortTasks(tasks, sortBy);
    this.isWritingFile = true;
    try {
      await this.app.vault.modify(file, newContent);
      this.fileCache[file.path] = newContent.split(/\r?\n/);
      new import_obsidian.Notice(`Tasks structured & sorted by ${sortBy === "due" ? "due date" : "priority"}!`);
    } catch (err) {
      new import_obsidian.Notice("Failed to organize tasks!");
      console.error(err);
    } finally {
      this.isWritingFile = false;
    }
  }
  /**
   * Moves all completed tasks (starting with x) to the completed archive file.
   */
  async archiveCompletedTasks() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView || !activeView.file) {
      new import_obsidian.Notice("No active file open!");
      return;
    }
    const file = activeView.file;
    if (!this.isTargetFile(file.path)) {
      new import_obsidian.Notice("Active file is not a designated Todo.txt file!");
      return;
    }
    const content = await this.app.vault.read(file);
    const lines = content.split(/\r?\n/);
    let inboxLines = 0;
    for (let i = 0; i < Math.min(3, lines.length); i++) {
      if (lines[i].trim().length === 0) {
        inboxLines++;
      } else {
        break;
      }
    }
    const uncompletedTasks = [];
    const completedTasks = [];
    for (let i = inboxLines; i < lines.length; i++) {
      const line = lines[i];
      const trimmed = line.trim();
      if (trimmed.length === 0)
        continue;
      if (trimmed.startsWith("#") || trimmed === "---") {
        uncompletedTasks.push(line);
        continue;
      }
      const task = parseTodoLine(line);
      if (task.completed) {
        completedTasks.push(line);
      } else {
        uncompletedTasks.push(line);
      }
    }
    if (completedTasks.length === 0) {
      new import_obsidian.Notice("No completed tasks found to archive!");
      return;
    }
    const archivePath = this.settings.archivePath || "completed_todo.md";
    let archiveFile = this.app.vault.getAbstractFileByPath(archivePath);
    this.isWritingFile = true;
    try {
      let archiveContent = "";
      if (archiveFile instanceof import_obsidian.TFile) {
        archiveContent = await this.app.vault.read(archiveFile);
      }
      let updatedArchiveContent;
      if (archiveContent.length > 0) {
        updatedArchiveContent = archiveContent + "\n\n---\n\n" + completedTasks.join("\n");
      } else {
        updatedArchiveContent = completedTasks.join("\n");
      }
      if (archiveFile instanceof import_obsidian.TFile) {
        await this.app.vault.modify(archiveFile, updatedArchiveContent);
      } else {
        await this.app.vault.create(archivePath, updatedArchiveContent);
      }
      const inboxPrefix = "\n\n\n";
      const updatedActiveContent = inboxPrefix + uncompletedTasks.join("\n");
      await this.app.vault.modify(file, updatedActiveContent);
      this.fileCache[file.path] = uncompletedTasks;
      new import_obsidian.Notice(`Archived ${completedTasks.length} task(s) to ${archivePath}!`);
    } catch (err) {
      new import_obsidian.Notice("Failed to archive tasks!");
      console.error(err);
    } finally {
      this.isWritingFile = false;
    }
  }
};
var TodoControlPanelModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Todo.txt Tasks Control Panel", cls: "todo-modal-title" });
    contentEl.createEl("p", {
      text: "Select an operation to apply to your current active Todo.txt note.",
      cls: "todo-modal-subtitle"
    });
    const buttonContainer = contentEl.createDiv({ cls: "todo-modal-buttons" });
    const createActionButton = (name, icon, action, description) => {
      const btnWrapper = buttonContainer.createDiv({ cls: "todo-action-wrapper" });
      const btn = btnWrapper.createEl("button", { cls: "todo-action-btn" });
      const iconSpan = btn.createSpan({ cls: "todo-btn-icon" });
      iconSpan.textContent = icon;
      const textSpan = btn.createSpan({ cls: "todo-btn-text", text: name });
      btn.addEventListener("click", () => {
        action();
        this.close();
      });
      btnWrapper.createEl("span", { cls: "todo-action-desc", text: description });
    };
    createActionButton(
      "Sort by Due Date",
      "\u{1F4C5}",
      () => this.plugin.processActiveFile("due"),
      "Group tasks under ## @context and ### +project, and sort by earliest due date."
    );
    createActionButton(
      "Sort by Priority",
      "\u{1F525}",
      () => this.plugin.processActiveFile("priority"),
      "Group tasks under ## @context and ### +project, and sort by priority (A) to (Z)."
    );
    createActionButton(
      "Archive Completed Tasks",
      "\u{1F4E5}",
      () => this.plugin.archiveCompletedTasks(),
      "Move all completed tasks (starting with 'x') into your configured archive file."
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var TodoSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Todo.txt Plugin Settings" });
    containerEl.createEl("h3", { text: "File Targeting" });
    new import_obsidian.Setting(containerEl).setName("Primary Todo File Path").setDesc("The primary target file for your Todo.txt tasks (relative to vault root).").addText(
      (text) => text.setPlaceholder("todo.md").setValue(this.plugin.settings.todoPath).onChange(async (value) => {
        this.plugin.settings.todoPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Additional Target Files").setDesc("Comma-separated list of other files in your vault to target (relative to vault root).").addText(
      (text) => text.setPlaceholder("work_todo.md, personal_todo.md").setValue(this.plugin.settings.additionalPaths).onChange(async (value) => {
        this.plugin.settings.additionalPaths = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Archive File Path").setDesc("Completed tasks will be archived/moved into this file.").addText(
      (text) => text.setPlaceholder("completed_todo.md").setValue(this.plugin.settings.archivePath).onChange(async (value) => {
        this.plugin.settings.archivePath = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Syntax Highlighting & Color Coding" });
    containerEl.createEl("p", {
      text: "Customize the hex colors of your Todo.txt components in target files.",
      cls: "setting-instructions-text"
    });
    const createColorPickerSetting = (name, desc, key) => {
      const setting = new import_obsidian.Setting(containerEl).setName(name).setDesc(desc);
      const colorInput = setting.controlEl.createEl("input", {
        type: "color",
        cls: "todo-color-picker-input"
      });
      colorInput.value = this.plugin.settings[key];
      const hexInput = setting.controlEl.createEl("input", {
        type: "text",
        cls: "todo-color-hex-input"
      });
      hexInput.value = this.plugin.settings[key];
      hexInput.maxLength = 7;
      colorInput.addEventListener("input", async (e) => {
        const val = e.target.value;
        hexInput.value = val;
        this.plugin.settings[key] = val;
        await this.plugin.saveSettings();
      });
      hexInput.addEventListener("change", async (e) => {
        let val = e.target.value;
        if (!val.startsWith("#"))
          val = "#" + val;
        if (/^#[0-9A-F]{6}$/i.test(val)) {
          colorInput.value = val;
          this.plugin.settings[key] = val;
          await this.plugin.saveSettings();
        } else {
          new import_obsidian.Notice("Invalid Hex color code! Format must be #RRGGBB");
          hexInput.value = this.plugin.settings[key];
        }
      });
    };
    createColorPickerSetting("Priority Color", "Color for priorities (e.g. (A), (B))", "priorityColor");
    createColorPickerSetting("Due Date Color", "Color for due dates (e.g. due:2026-05-24)", "dueDateColor");
    createColorPickerSetting("Overdue / Due Today Color", "Color for overdue or due today tasks (e.g. due:2026-05-23)", "overdueDateColor");
    createColorPickerSetting("Project Color", "Color for projects (e.g. +ProjectName)", "projectColor");
    createColorPickerSetting("Context Color", "Color for contexts (e.g. @contextName)", "contextColor");
    createColorPickerSetting("Recurrence Color", "Color for recurrence tags (e.g. rec:1w)", "recColor");
  }
};
